from StateSchema import ResearchSchema
from llm_core import LLM






def critic_agent(state: ResearchSchema,llm: LLM)-> ResearchSchema:
    prompt= f"""
    Original Query: {state['query']}
    Draft: {state['draft']}
    You are a critic agent tasked to review the draft generated by the writer agent. 
    Critique the draft based on the original query. 
    respond only with the word "true" if result is approved or "false" if result is not approved based on the quality of the draft .
    """
    
    critique = llm.generate_response(prompt)
    
    if critique.content.strip().lower() == "true":
        state["approved"] = True
    else:
        state["approved"] = False
    
    return state