from langchain_ollama import ChatOllama

class LLM():
    def __init__(self):
        self.llm= ChatOllama(
            model="qwen3.5:9b",
            reasoning=False
        )

    def generate_response(self, prompt: str) -> str:
        """
        generate_response is a function that takes a prompt and returns a response generated by the LLM.
        It uses the ChatOllama model to generate the response.
        """
        response = self.llm.invoke(prompt)
        return response
    